### ISSUE TITLE
Running basic example, no plot, no class

### ISSUE THREAD

**Issue by 0x3W** [mrocklin/streamz#167]
Library is awesome, well done Mr. Rocklin. But I have issue running basic example:

- following [github example](https://github.com/mrocklin/streamz/blob/master/examples/dataframes.ipynb) produces empty Bokeh plot which You may see [here](https://ibb.co/kTZxhS)

- following [blog example](http://matthewrocklin.com/blog/work/2017/10/16/streaming-dataframes-1) produces following error:

ImportError: cannot import name 'StreamingDataFrame'

So I'd just like to run a streaming data frame and plot it, as shown in examples. Any idea what I am doing wrong?

**Comment by martindurant** [comment]
Plotting is being pulled out of streamz and into [holoplot](https://github.com/pyviz/holoplot) which will provide the same interface across many different data sources. You can either call its 'path' function to have it attached to a stream's `plot()` method as before, or call it directly. For examples, see https://github.com/pyviz/holoplot/blob/master/examples/user_guide/Streaming_Plots.ipynb

Clearly we should update the doc/examples on our.

**Comment by 0x3W** [comment]
@martindurant thank You for explaining. I'd like to skip installing conda for running an example because I always have some issues with pip and conda and python. And seems its not possible to install holoplot without it. Notebook looks good and hopefully with time HoloPlot becomes possible to install without conda and docs update. And I run example :) Nontheless, looks amazing and promising!

**Comment by mrocklin** [comment]
> And seems its not possible to install holoplot without it.

That seems surprising. You might want to verify that assumption by checking
in with that library.

**Comment by 0x3W** [comment]
Thanks for quick reply. Maybe its just my lack of skills but I've followed this [guide](https://github.com/pyviz/holoplot/blob/master/doc/getting_started/index.rst) from their github, and it specifies environment in .yml and I am not sure how to adjust installation without conda command to install dependencies, and without it, it doesnt install. 

Maybe there is some better guide on installing it?

**Comment by mrocklin** [comment]
I recommend asking them

On Apr 20, 2018 11:35 AM, "Dovla" <notifications@github.com> wrote:

Thanks for quick reply. Maybe its just my lack of skills but I've followed
this guide
<https://github.com/pyviz/holoplot/blob/master/doc/getting_started/index.rst>
from their github, and it specifies environment in .yml and I am not sure
how to adjust installation without conda command to install dependencies,
and without it, it doesnt install.

Maybe there is some better guide on installing it?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mrocklin/streamz/issues/167#issuecomment-383042520>,
or mute
the thread

**Comment by 0x3W** [comment]
Thank You @mrocklin @martindurant 

I finally managed to run it, though installed the packaged manually.
