### ISSUE TITLE
Streamz API confusion or possible bug.

### ISSUE THREAD

**Issue by daniel-severo** [mrocklin/streamz#186]
**(tried to ask this on stackoverflow but looks like the "streamz" tag hasn't been created yet)**

Take for instance the following code:

```python3
from streamz import Stream
import time

def inc(x):
    time.sleep(1)
    return x+1
    
source = Stream()
    
mult = source.map(inc)
mult.sink(print) #1
mult.sink(source.emit) #2

source.visualization(rankdir="LR")
```

[![enter image description here][1]][1]

On calling `source.emit(0)` it starts printing out integers incrementally starting at 1, which is what I expect.

On changing the order of `#1` with `#2` (resulting in the same graph) the code blocks and nothing is printed out. 

As far as I was understanding, each time I chain a method to a `Stream` object I'm adding stages to it getting back a reference of said pipeline at some point in the graph (so for example, `mult` refers to the outgoing edges of the `(map; inc)` node).

Is this a bug or am I missing something?

Thanks!

  [1]: https://i.stack.imgur.com/MU40o.png

**Comment by CJ-Wright** [comment]
I don't think this is a bug, but it is an interesting use case.
So what is happening is that since the emit triggers before the print then the emit has an infinite loop which never gets around to performing the print.

The `source_node = True` option for visualization will help with this by numbering branches by their execution order so you can see what is done first.

**Comment by daniel-severo** [comment]
Thanks! I've been using dask so much for the past few months I forgot that this was sequential.

Yeah, pretty interesting way to highlight this specific pitfall.
