### ISSUE TITLE
Union streams by key

### ISSUE THREAD

**Issue by gte620v** [mrocklin/streamz#203]
Is there a way in streamz to implement the functionality described in https://stackoverflow.com/a/28509393/5058588?

I have to timestamped streams that flow at different rates and I'd like to create an interleaved output of these two streams that is sorted by timestamp.

**Comment by CJ-Wright** [comment]
Are the timestamps monotonic? If so maybe this could be done via an accumulator which checks the timestamps of the current element in state and the new element. If the new element is newer than the state, emit the state and then make the new element the state otherwise emit the new element and keep the state.

**Comment by gte620v** [comment]
Ah, yes, good suggestion.  thanks.
