### ISSUE TITLE
Are the basic stream single threaded?

### ISSUE THREAD

**Issue by xray1111** [mrocklin/streamz#237]
I'm excited to see this project is flourishing! Thank you!

But it seems that the basic stream only running in a single thread, no matter how many downstreams are forked. I'm not very sure about this. If it is, do you have any plan to enhance the parallelism if the local machine has multi-core?

**Comment by CJ-Wright** [comment]
Yes, the core stream nodes execute one at a time. If you'd like parallel execution you might consider using scatter and gather nodes, which use a dask client to perform parallel execution. Please see the dask section for more details: https://streamz.readthedocs.io/en/latest/dask.html

**Comment by xray1111** [comment]
Suppose there is a such use case: a stream need to be grouped and fork to different downstream processing, due to some special strategy. If you turn it into a dask stream using scatter at the front end, you may not apply different process step according to different stream element? Since scatter function randomly send elements to different dask stream, I guess?

**Comment by martindurant** [comment]
Worth pointing out that much of streamz' work is actually asynchronous - several things happen concurrently, but not in parallel. By this, I mean that tasks are assigned to the event loop, but executed whenever there is time (think of this as "cooperative multitasking"). So long as each function call is short, this is good enough for most applications, with very high message throughput.

**Comment by CJ-Wright** [comment]
@xray1111 the `scatter` node doesn't send things randomly, the pipeilne preserves ordering since it passes futures around in order. If the data processing graph has forks and joins then dask should respect that multiple pieces of data are needed to compute the results. If there are no joins then there should be no dependencies between the data (operation a (eg. save to database) doesn't interact with process b (eg. visualize the data)).

Do you have an example graph for what you are trying to do? If you could post it here that would be very helpful.

**Comment by xray1111** [comment]
Thanks again guys, I'll look into the dask document.
